server:
  port: 9090
  error:
    whitelabel:
      enabled: false
    path: /index.html

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: http://${cors.allowed-origins}
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      server:
        webflux:
          routes:
            # API INVENTARIO
            - id: products
              uri: http://${INVENTORY_IP:localhost}:8081
              predicates:
                - Path=/api/v1/products/**

            - id: branches
              uri: http://${INVENTORY_IP:localhost}:8081
              predicates:
                - Path=/api/v1/branches/**

            - id: warehouses
              uri: http://${INVENTORY_IP:localhost}:8081
              predicates:
                - Path=/api/v1/warehouses/**

            # API PEDIDOS
            - id: orders
              uri: http://${ORDERS_IP:localhost}:8081
              predicates:
                - Path=/api/v1/orders/**

            # API USUARIOS
            - id: users
              uri: http://${USERS_IP:localhost}:8081
              predicates:
                - Path=/api/v1/users/**

            - id: roles
              uri: http://${USERS_IP:localhost}:8081
              predicates:
                - Path=/api/v1/roles/**

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
