server:
  port: 9090
  error:
    whitelabel:
      enabled: false
    path: /index.html

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: ${cors.allowed-origins}
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      server:
        webflux:
          routes:
            # API INVENTARIO
            - id: products
              uri: http://${INVENTORY_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/products/**

            - id: branches
              uri: http://${INVENTORY_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/branches/**

            - id: warehouses
              uri: http://${INVENTORY_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/warehouses/**

            # API PEDIDOS
            - id: orders
              uri: http://${ORDERS_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/orders/**

            # API USUARIOS
            - id: users
              uri: http://${USERS_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/users/**

            - id: roles
              uri: http://${USERS_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/roles/**

                # SWAGGER INVENTARIO
            - id: inventory-docs
              uri: http://${INVENTORY_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/inventario/v3/api-docs
              filters:
                - RewritePath=/inventario/v3/api-docs, /v3/api-docs

            # SWAGGER PEDIDOS
            - id: orders-docs
              uri: http://${ORDERS_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/pedidos/v3/api-docs
              filters:
                - RewritePath=/pedidos/v3/api-docs, /v3/api-docs

            # SWAGGER USUARIOS
            - id: users-docs
              uri: http://${USERS_IP:localhost}:${MICROSERVICE_PORT:8081}
              predicates:
                - Path=/usuarios/v3/api-docs
              filters:
                - RewritePath=/usuarios/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Inventario API
        url: /inventario/v3/api-docs
      - name: Pedidos API
        url: /pedidos/v3/api-docs
      - name: Usuarios API
        url: /usuarios/v3/api-docs

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
